development: &defaults
  adapter: postgresql
  encoding: unicode
  database: earthquaker_development
  pool: 5

test:
  <<: *defaults
  database: earthquaker_test

production:
  <<: *defaults
  database: earthquaker_production
